server {
    listen 443 ssl;
    server_name jus-srv-test30.justiz.sachsen.de;

    ssl_certificate     /etc/ssl/certs/jus-srv-test30.justiz.sachsen.de.crt;
    ssl_certificate_key /etc/ssl/private/jus-srv-test30.justiz.sachsen.de.pk.un_encrypted.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # optional: statische Dateien direkt ausliefern
    location /static/ {
        expires 1y;
        access_log off;
    }
}
