services:
  frontend:
    restart: unless-stopped
    build: 
      context: ${PROJECT_PATH}/frontend
      dockerfile: Dockerfile
      pull: false
      args:
        PROJECT_PATH: ${PROJECT_PATH}
        PATH_TO_TLS: ${PATH_TO_TLS}
    environment:
      - REACT_APP_BACKEND_URL=https://${IP}:${BACKEND_PORT}
      - HTTPS=true
      - SSL_CRT_FILE=/usr/src/app/tls/jus-srv-test30.justiz.sachsen.de.crt
      - SSL_KEY_FILE=/usr/src/app/tls/jus-srv-test30.justiz.sachsen.de.pk.un_encrypted.pem
      - PORT=${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - ${NETWORK}
    depends_on:
      - backend
      - database

#  cypress:
#    build:
#      context: ${PROJECT_PATH}/cypress
#      pull: false
#    
#    networks:
#      - ${NETWORK}
#    depends_on:
#      - frontend
#      - backend
#    entrypoint: ["npx", "cypress", "run"]

  backend:
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json 
      - ${BACKEND_LOGS}:/usr/src/app/logs
    build: 
      context: ${PROJECT_PATH}/backend
      dockerfile: Dockerfile
      pull: false
      
      args:
        PROJECT_PATH: ${PROJECT_PATH}
        BACKEND_PORT: ${BACKEND_PORT}
        PATH_TO_TLS: ${PATH_TO_TLS}
    ports:
      - ${BACKEND_PORT}:8080
    networks:
      - ${NETWORK}
    environment:
      - SPRING_PROFILES_ACTIVE=${IP}:${DATABASE_PORT}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PW_TLS=${PW_TLS}
      - PW_DB=${PW_DB}
      - HTTP_PROXY=http://proxy.justiz.sachsen.de:3128
      - HTTPS_PROXY=http://proxy.justiz.sachsen.de:3128

  database:
    restart: unless-stopped
    build: 
      context: ${PROJECT_PATH}/database
      dockerfile: Dockerfile
      pull: false
      args:
        PROJECT_PATH: ${PROJECT_PATH}
    environment:
      MYSQL_DATABASE: mydatabase
      PW_DB: ${PW_DB}
      MARIADB_ROOT_PASSWORD: ${PW_DB}
    networks:
      - ${NETWORK}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ${VOLUME}:/var/lib/mysql
      - ${DB_LOGS}:/var/log/mysql/
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 10s
      retries: 5
      timeout: 10s

networks:
  mynetwork_dev:
    driver: bridge
  mynetwork:
    driver: bridge

volumes:
  mariadb_data_dev:
  mariadb_data:
  logs_dev:
  logs:
  logs_dev_backend:
  logs_backend:
