services:
  frontend:
    restart: unless-stopped
    build: 
      context: /
      dockerfile: ${PROJECT_PATH}/frontend/Dockerfile
      args:
        PROJECT_PATH: ${PROJECT_PATH}
        PATH_TO_TLS: ${PATH_TO_TLS}
    environment:
      - REACT_APP_BACKEND_URL=https://${IP}:${BACKEND_PORT}
      - HTTPS=true
      - SSL_CRT_FILE=/usr/src/app/tls/jus-srv-test30.justiz.sachsen.de.crt
      - SSL_KEY_FILE=/usr/src/app/tls/jus-srv-test30.justiz.sachsen.de.pk.un_encrypted.pem
      - PORT=${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - ${NETWORK}
    depends_on:
      - backend
      - database

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "3000:3000"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./ca/desksharingtool/desksharingtool.crt:/etc/nginx/ssl/cert.pem:ro
  #     - ./ca/desksharingtool/desksharingtool_unencrypted.key:/etc/nginx/ssl/cert.key:ro
  #   networks:
  #     - ${NETWORK}

  backend:
    #restart: unless-stopped
    privileged: true
    #command: mvn test
    #stdin_open: true
    #tty: true
    volumes:
      #- ./test-results:/foo:rw
      #- $HOME/.docker/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json 
      #- /home/r/.m2:/root/.m2
    build: 
      context: /
      dockerfile: ${PROJECT_PATH}/backend/Dockerfile 
      args:
        PROJECT_PATH: ${PROJECT_PATH}
        BACKEND_PORT: ${BACKEND_PORT}
        PATH_TO_TLS: ${PATH_TO_TLS}
    ports:
      - ${BACKEND_PORT}:8080
    networks:
      - ${NETWORK}
    #depends_on:
     # - database
    environment:
      - SPRING_PROFILES_ACTIVE=${IP}:${DATABASE_PORT}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PW_TLS=${PW_TLS}
      - PW_DB=${PW_DB}
      - HTTP_PROXY=http://proxy.justiz.sachsen.de:3128
      - HTTPS_PROXY=http://proxy.justiz.sachsen.de:3128
    #command: mvn test
#    healthcheck:
#      test: ["CMD", "ping", "-c", "1", "localhost"]
#      interval: 10s
#      retries: 5
#      timeout: 10s

  database:
    restart: unless-stopped
    build: 
      context: /
      dockerfile: ${PROJECT_PATH}/database/Dockerfile
      args:
        PROJECT_PATH: ${PROJECT_PATH}
    environment:
      MYSQL_DATABASE: mydatabase
      PW_DB: ${PW_DB}
      MARIADB_ROOT_PASSWORD: ${PW_DB}
    networks:
      - ${NETWORK}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ${VOLUME}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 10s
      retries: 5
      timeout: 10s

networks:
  mynetwork_dev:
    driver: bridge
  mynetwork:
    driver: bridge

volumes:
  mariadb_data_dev:
  mariadb_data:
