#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Oct 11 18:02:12 CEST 2024
maven-metadata-central.xml.error=Could not transfer metadata org.springframework.boot\:spring-boot-maven-plugin/maven-metadata.xml from/to central (https\://repo.maven.apache.org/maven2)\: Das Netzwerk ist nicht erreichbar
maven-metadata-central.xml/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1728662532048
