
error_log /var/log/nginx/error.log debug;
server {
    listen 443 ssl http2;
    server_name jus-srv-test30;

    #do not send server version info
    server_tokens off;

    ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1;
#    ssl_ciphers EECDH+AESGCM:EECDH+AES256;
#    ssl_prefer_server_ciphers on;

    error_log /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;

    # Path for SSL config/key/certificate
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/cert.key;

    # location /eas {
    #     root /eas-visual;
    #     autoindex on;
    #     autoindex_exact_size off;
    #     autoindex_format html;
    #     autoindex_localtime on;
    # }

    # location / {
    #     proxy_pass https://mantisfstar.scm.justiz.sachsen.de;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }


    access_log off;
    error_log /var/log/nginx/error.log error;
}

server {
    listen 80 default_server;
    server_name jus-srv-test30;

    #do not send server version info
    server_tokens off;

    error_log /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;

    # location /eas {
    #     root /eas-visual;
    # }

    # location / {
    #     proxy_pass https://mantisfstar.scm.justiz.sachsen.de;
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    access_log off;
    error_log /var/log/nginx/error.log error;
    server_name _;
}
