
error_log /var/log/nginx/error.log debug;
server {
    listen 3000;
    location /ws {
        proxy_pass https://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
