spring.datasource.url=jdbc:mariadb://database:3306/mydatabase
spring.datasource.password=${PW_DB}
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
# Errors
spring.web.resources.add-mappings=false

# Hibernate settings
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=DEBUG
# Set the logging level for the root logger (DEBUG, INFO, WARN, ERROR, TRACE)
logging.level.root=INFO

# Set logging level for specific packages
#logging.level.com.example.myapp=DEBUG

# Logging pattern for the console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Set the path for the log file
logging.file.name=logs/backend.log

# Max log file size
logging.logback.rollingpolicy.max-file-size=10MB

# Total size of all log files
logging.logback.rollingpolicy.total-size-cap=300MB

# TLS
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:tls/jus-srv-test30.justiz.sachsen.de.p12
server.ssl.key-store-password=${PW_TLS}