spring.datasource.url=jdbc:tc:mariadb:10.6:///test
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
logging.level.org.testcontainers=DEBUG